config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EUDAT-B2HANDLE/PYHANDLE:
      branch: master
      repo: https://github.com/EUDAT-B2HANDLE/PYHANDLE.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE git:
        commands:
        - /usr/bin/env sh .sqa/script.ice_focused_hydra.sh
        container: qc.acc_eggplant_determined_barracuda
  QC.Doc:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.incarnadine_sympathetic_puffin.sh
        container: qc.doc_reef_confused_snail
      github.com/EUDAT-B2HANDLE/PYHANDLE git:
        commands:
        - /usr/bin/env sh .sqa/script.cream_upbeat_crane.sh
        container: qc.doc_porcelain_determined_lynx
      github.com/EUDAT-B2HANDLE/PYHANDLE markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.aquamarine_grateful_crocodile.sh
        container: qc.doc_tundra_blissful_rhinoceros
      github.com/EUDAT-B2HANDLE/PYHANDLE restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.currant_peppy_rattlesnake.sh
        container: qc.doc_butter_innocent_llama
  QC.Lic:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE licensee:
        commands:
        - /usr/bin/env sh .sqa/script.peach_sweet_lynx.sh
        container: qc.lic_pansy_organized_gull
  QC.Sec:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE bandit:
        commands:
        - /usr/bin/env sh .sqa/script.mango_courageous_viper.sh
        container: qc.sec_cayenne_positive_phoenix
  QC.Sty:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE flake8:
        commands:
        - /usr/bin/env sh .sqa/script.daffodil_fearless_jackal.sh
        container: qc.sty_mauve_reflective_griffin
      github.com/EUDAT-B2HANDLE/PYHANDLE hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fog_whimsical_dragonfly.sh
        container: qc.sty_grape_zany_emu
      github.com/EUDAT-B2HANDLE/PYHANDLE jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jade_enthusiastic_wolf.sh
        container: qc.sty_blush_impulsive_gull
  QC.Uni:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ceru_sarcastic_wolverine.sh
        container: qc.uni_cornflower_whimsical_clownfish
  QC.Ver:
    repos:
      github.com/EUDAT-B2HANDLE/PYHANDLE get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.incarnadine_smart_opossum.sh
        container: qc.ver_slate_unique_panther
timeout: 5400
